"""
ota_server.py - publishes the manifest and firmware chunks over MQTT.

Expects manifest.json and the chunk files it lists (chunk0..chunk3) to already
exist, generated by the firmware processor.

  Topics:  ota/rpi4/manifest         manifest (JSON)
           ota/rpi4/chunk/<index>    {"version", "index", "data": base64}
  QoS:     1 (at least once); duplicates are handled by the client.
  Retain:  True, so a client that subscribes later still gets everything.
"""

import base64
import json
import sys
import threading
from sys import path
from pathlib import Path

from paho.mqtt import client as mqtt_client


BROKER = sys.argv[1] if len(sys.argv) > 1 else "localhost"
PORT = 1883
QOS = 1
MANIFEST_FILE = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("manifest.json")
MANIFEST_TOPIC = "ota/rpi4/manifest"
CHUNK_TOPIC = "ota/rpi4/chunk"
CLIENT_ID = "ota-server"


def connect_mqtt():
    connected = threading.Event()

    def on_connect(client, userdata, flags, reason_code, properties):
        if reason_code.is_failure:
            print(f"Failed to connect, return code {reason_code}")
        else:
            print("Connected to MQTT Broker!")
            connected.set()

    client = mqtt_client.Client(
        client_id=CLIENT_ID,
        callback_api_version=mqtt_client.CallbackAPIVersion.VERSION2,
    )
    client.on_connect = on_connect
    client.connect(BROKER, PORT)
    client.loop_start()
    if not connected.wait(timeout=10):
        client.loop_stop()
        raise ConnectionError(f"Could not connect to {BROKER}:{PORT}")
    return client


def publish(client, manifest):
    messages = [(MANIFEST_TOPIC, manifest)]
    for entry in manifest["data"]:
        with open(MANIFEST_FILE.parent / entry["filename"], "rb") as file:
            chunk = file.read()
        payload = {
            "version": manifest["version"],
            "index": entry["index"],
            "data": base64.b64encode(chunk).decode("ascii"),
        }
        messages.append((f"{CHUNK_TOPIC}/{entry['index']}", payload))

    infos = []
    for topic, payload in messages:
        info = client.publish(topic, json.dumps(payload), qos=QOS, retain=True)
        infos.append((topic, info))

    # status 0 only means queued; wait for the broker's acknowledgement.
    for topic, info in infos:
        info.wait_for_publish(timeout=10)
        if info.is_published():
            print(f"Sent to topic `{topic}`")
        else:
            print(f"Failed to send message to topic {topic}")


def run():
    with open(MANIFEST_FILE) as file:
        manifest = json.load(file)
    client = connect_mqtt()
    try:
        publish(client, manifest)
    finally:
        client.loop_stop()
        client.disconnect()


if __name__ == "__main__":
    run()